[build]
  command = "npm run build"  # Next.js build command
  publish = ".next"          # Next.js output directory
  functions = "netlify/functions"  # Directory for serverless functions

[dev]
  autoLaunch = false

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]
