[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium", "googleapis", "node-fetch", "uuid"]

[functions.emails]
  background = true

[dev]
  autoLaunch = false