[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium", "googleapis", "node-fetch", "uuid"]

[functions.emails]
  background = true

[functions.emails-background]
  background = true

[dev]
  autoLaunch = false

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_FUNCTIONS_URL = "https://rahat-crawl.netlify.app/.netlify/functions"