export const MAXDEPTH: number = 2;
export const MAXPAGESPERPREFIX: number = 3;
export const MAXCONCURRENTPAGES: number = 2;
const COMMON_IGNOREKEYWORDS = [
  "privacy",
  "terms",
  "cookie",
  "legal",
  "#",
  "disclaimer",
  "policy",
  "hire",
  "drupal",
  "joomla",
  "wordpress",
  "cms",
  "power-bi",
  "tableau",
  "xamarin",
  "ecommerce",
  "flutter",
  "react-native",
  "android",
  "ios",
  "mobile-app",
  "vuejs",
  "laravel",
  "angular",
  "java",
  "php",
  "dotnet",
  "python",
  "shopify",
  "nopcommerce",
  "guides/tag/",
  "outsourcing",
  "roi",
  "brochures",
  "winwithai",
  "newsletter",
  "partner",
  "webinar",
  "custom",
  "studies",
  "study",
  "blog",
  "sitemap",
  "videos",
  "news",
  "events",
  "press",
  "resources",
  "tags",
  "white",
  "trends",
];
export const COVERLETTER_IGNOREKEYWORDS = [
  ...COMMON_IGNOREKEYWORDS,
  "free-trial",
  "pricing",
];

export const CONTACTS_IGNOREKEYWORDS = [
  ...COMMON_IGNOREKEYWORDS,
  "nodejs",
  "full-stack",
  "back-end",
  "front-end",
  "faq",
];
